config/routes.rb
Rails.application.routes.draw do
  get 'pins/index'

  devise_for :users, :path => 'accounts'
  root to: 'pins#allpins'



  get 'pins/allpins', to: 'pins#allpins'
  resources :pins

  resources :users

end

app/models/pin.rb
class Pin < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  def username
    self.email.split('@')[0].capitalize
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController

  def index
    @pins = Pin.all
  end

  def show
    @pin = Pin.find(params[:id])
  end

  def allpins
    @pins = Pin.all
  end

  def new
    @pin = Pin.new
  end

  def create
    @pin = Pin.create!(pin_params)
    redirect_to pins_path
  end

  def edit
    @pin = Pin.find(params[:id])
    redirect_to pins_path
  end



  private

  def pin_params
    params.require(:pin).permit(:title, :img_url)
  end

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    # @pins = @user.pins
  end

  def show

  end

  private
  def set_user
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinspiration</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <h1>Pinspiration</h1>

  <% if current_user %>
   <h3><%= link_to 'Signout', destroy_user_session_path, :method => :delete %></h3>

  <% else %>
   <h3><%= link_to 'Signup', new_user_registration_path %></h3>
   <h3><%= link_to 'Login', new_user_session_path %></h3>
  <% end %>
  <% if current_user %>
  <h3><%= link_to 'Go to my Pins', users_path %></h3>
  <% end %>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/pins/_form.html.erb
 <%= form_for @pin do |f| %>

     <%= f.label :img_url %>
     <%= f.text_field :img_url %>


     <%= f.label :title %>
     <%= f.text_area :title %>


     <%= f.submit %>

 <% end %>

app/views/pins/allpins.html.erb
<h2>Pins</h2>

<% @pins.each do |pin| %>
<div class="each_pin">
    <%= image_tag pin.img_url, class: "pin_image"%>
  <div class="pin_title">
    <%= pin.title %>
  </div>
</div>
<% end %>



<%= link_to 'Create New Pin', new_pin_path(@pin) %>

app/views/pins/edit.html.erb
<h1>Edit Pin</h1>

<%= render'form' %>
<%= link_to 'back', pins_path %>

app/views/pins/index.html.erb
<% @pins.each do |pin| %>
<div class="each_pin">
    <%= image_tag pin.img_url, class: "pin_image"%>
  <div class="pin_title">
    <%= link_to pin.title, pin_path(pin) %>
  </div>
</div>


<% end %>

app/views/pins/new.html.erb
<h1>New Pin</h1>

<%= render'form' %>
<%= link_to 'back', pins_path %>

app/views/pins/show.html.erb
<%= image_tag pin.img_url, class: "pin_image"%>

<%= link_to pin.title, edit_pin_path(@pin) %>

app/views/users/index.html.erb
<h2><%= @user.username %>'s Pins</h2>


<% @pins.each do |pin| %>
<div class="each_pin">
    <%= image_tag pin.img_url, class: "pin_image"%>
  <div class="pin_title">
    <%= pin.title %>
  </div>
</div>
<% end %>